apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80        # Port exposed by the service
    targetPort: 80  # Port where the application is running in the pod
    nodePort: 30082 # NodePort that will expose the service on all cluster nodes
