apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  containers:
  - name: redis
    image: redis
  initContainers:
  - name: init-sleep
    image: busybox
    command: ['sh', '-c', 'echo Sleeping for 20 seconds... && sleep 20']