apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webapp-container
    image: nginx
    volumeMounts:
    - name: log-storage
      mountPath: /var/log/nginx
  volumes:
  - name: log-storage
    persistentVolumeClaim:
      claimName: claim-log-1
